# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/smarterhq/shq_pre-commit_hooks
    rev: a76ef7944652b491e02f1382be3083e821e34e92
    hooks:
      - id: shellcheck
      - id: hadolint
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args: ["-l 200"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-import-order, flake8-docstrings]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        args: ["--print-width=200", "--prose-wrap=preserve"]
